# Numpy Basics

In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
a.shape

(5,)

In [6]:
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [7]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
a = np.zeros((3,3))
b = np.ones((2,3))
c = np.full((3,2), 5)
d = np.eye(4)
e = np.random.random((2,3))
print(a)
print(b)
print(c)
print(d)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.29947396 0.38745403 0.70008139]
 [0.49735536 0.27787177 0.66260319]]


In [9]:
print(e[:, 2])

[0.70008139 0.66260319]


In [11]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [12]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [13]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [14]:
np.multiply(x,y) # ElementWise

array([[ 5, 12],
       [21, 32]])

In [15]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [16]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [17]:
np.dot(x, y) # Matrix Multiplication

array([[19, 22],
       [43, 50]])

In [18]:
np.sum(x)

10

In [19]:
np.sum(x, axis=1)

array([3, 7])

In [23]:
a = np.array([1,2,3,4])

In [24]:
b = np.array([4,5,6,7])

In [25]:
np.stack((a,b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [26]:
np.stack((a,b), axis=0)

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [27]:
a.shape

(4,)

In [29]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

# Numpy Random Module

In [32]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [34]:
np.random.shuffle(a)
print(a)

[11 12  9  6  8  7 10 13 14  5]


In [36]:
a = np.random.rand(2,3)
print(a)

[[0.40210431 0.28094561 0.69990144]
 [0.39372324 0.14716736 0.48700305]]


In [37]:
a = np.random.randint(5, 10, 3)
print(a)

[5 9 6]


In [38]:
element = np.random.choice([1,3,4,6,7,8,9,2])
print(element)

4


In [43]:
np.random.seed(3)
np.random.shuffle(a)
print(a)

[6 5 9]


# Numpy Statistics

In [44]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [48]:
print(np.min(a))
print(np.min(a, axis=0))
print(np.min(a, axis=1))

1
[1 2 3 4]
[1 5]


In [49]:
print(np.mean(a))
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))

4.5
[3. 4. 5. 6.]
[2.5 6.5]


In [51]:
b = np.array([3,5,6,7,1])
print(np.median(b))

5.0


In [52]:
wts = np.array([1,2,3,4,5])
print(np.average(b, weights=wts))

4.266666666666667


In [53]:
np.std(b)

2.1540659228538015

In [54]:
np.var(b)

4.64

## Given a running stream of numbers, compute mean, std and variance at any given point.